### ISSUE TITLE
User and item id mappings are gone after applying filters

### ISSUE THREAD

**Issue by paraschakis** [LienM/recpack#1] opened 2023-02-17 13:44 UTC
The `apply` method of some filters returns a copy of the passed dataframe.
So when the `process_many` method of `DataFramePreprocessor` assigns `uid` and `iid`, it is no longer done on the original dataframe, but on its copy. And since this copy is not returned, the original dataframe is not affected. It will have no id mappings, and will not be filtered.

Potential fix: either do all dataframe manipulations inplace in filters, or return the modified dataframe from the `process` method.

**Comment by LienM** [comment] 2023-02-17 16:26
Hi @paraschakis, 

Thank you for reporting this issue. We have just created (and merged) a fix to master: https://gitlab.com/recpack-maintainers/recpack/-/merge_requests/188. Could you try the fix with your code to see if the issue is now resolved?
If not, we would greatly appreciate a minimal reproducible example. 

A new release of RecPack on PyPi is planned sometime next week, when we've merged the other open pull requests as well. I

Have a great weekend!
Lien

**Comment by paraschakis** [comment] 2023-02-20 09:49
Hi Lien,

Unfortunately, with the above the user and item ids are gone even when no filters are used.

Here is a minimal reproducible example:

```
import pandas as pd
import random
from recpack.preprocessing.preprocessors import DataFramePreprocessor
from recpack.preprocessing.filters import Deduplicate

#%%
# Create a dataframe with dummy user-item interaction data (with duplicates)
num_users = 1000
max_items_per_user = 100

users = [hex(random.randint(0, 2**32-1))[2:] for _ in range(num_users)]
items = [hex(random.randint(0, 2**32-1))[2:] for _ in range(num_users*max_items_per_user)]

interactions = []
for user in users:
    num_items = random.randint(1, max_items_per_user)
    user_items = random.choices(items, k=num_items)
    interactions.extend([(user, item) for item in user_items])

df = pd.DataFrame(interactions, columns=['user', 'item'])

#%%
# Preprocess data to construct interaction matrix
print(f'num interactions before filtering: {len(df)}')
preprocessor = DataFramePreprocessor('item', 'user')
preprocessor.add_filter(Deduplicate('item', 'user'))
interaction_matrix = preprocessor.process(df)
print(f'num interactions after filtering: {len(df)}')
```

If you run the code without the 'Deduplicate' filter, you will get user/item id mappings in the original dataframe. If you then run it **with** the filter, you'll notice that the original dataframe is unfiltered, and the user/item id mappings are missing.

To fix the issue for this particular filter, we can change its `apply` method as follows:

Original:
```
    def apply(self, df):
        if self.timestamp_ix is not None:
            df = df.sort_values(self.timestamp_ix)
        return df.drop_duplicates([self.user_ix, self.item_ix], keep="first")
```

Fixed:
```
    def apply(self, df):
        if self.timestamp_ix is not None:
            df.sort_values(self.timestamp_ix, inplace=True)
        df.drop_duplicates([self.user_ix, self.item_ix], keep="first", inplace=True)
        return df
```

**Comment by paraschakis** [comment] 2023-02-20 10:03
For me, the preferred fix would be if the `process` method of the `DataFramePreprocessor` returned both the interaction matrix and the modified dataframe. This way you would avoid changing the code of every filter, and also avoid changing the original dataframe (it felt a bit weird when I first noticed the added 'iid' and 'uid' columns in my source dataframe - why would anyone want to touch it?). However, I realize that this fix would introduce a breaking change.

**Comment by LienM** [comment] 2023-02-20 10:06
Hi @paraschakis,

Thank you for the minimal reproducible example here. The intended behavior is actually to never change the original DataFrame, and this bug was fixed on master. 

To get a filtered DataFrame with both the original user and item IDs and the mapped user and item IDs, you can use:

```
import pandas as pd
from recpack.preprocessing.preprocessors import DataFramePreprocessor
from recpack.preprocessing.filters import Deduplicate
from recpack.datasets import DummyDataset

# Create a dataset of dummy data easily
d = DummyDataset()
# Extract original DataFrame
df = d._load_dataframe()

# Create filtered InteractionMatrix
preprocessor = DataFramePreprocessor(d.USER_IX, d.ITEM_IX)
preprocessor.add_filter(Deduplicate(d.ITEM_IX, d.USER_IX))
interaction_matrix = preprocessor.process(df)

# Extract the underlying DataFrame from the InteractionMatrix
mapped_df = interaction_matrix._df
mapped_df.head()
```

However, note that the mapped_df is an internal attribute (denoted with the underscore) and so its behavior may change in future releases (although I don't expect this to be soon). 

Hope this helps
Lien

**Comment by paraschakis** [comment] 2023-02-20 10:14
Thanks for the code snippet! I totally misunderstood the intended behavior, sorry for that :)

**Comment by LienM** [comment] 2023-02-20 12:38
No worries! It's a valid question and we caught a bug thanks to your report! 
We'll be creating a FAQ when we've collected a few questions and answers and I'll put it in there for other people who have 
the same question.

Btw, RecPack 0.3.5 with the fix was just released: https://pypi.org/project/recpack/

Have a great week 👋 
Lien

**Closed by LienM** 2023-02-20 12:38 UTC
